# SPDX-License-Identifier: AGPL-3.0-or-later
name: BenchmarkRunner
channels:
  - conda-forge
  - nodefaults
  - pytorch
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - cpuonly
  - onnx
  - tensorflow
  - keras_applications
  # We don't like conda-forge's opencv packages, because they don't include
  # type stubs
  - pip:
    - opencv-python