# SPDX-License-Identifier: AGPL-3.0-or-later
name: BenchmarkRunner
channels:
  - conda-forge
  - nodefaults
  - pytorch
dependencies:
  - python
  - opencv
  - py-opencv
  - pytorch
  - torchvision
  - cpuonly