# SPDX-License-Identifier: AGPL-3.0-or-later
name: BenchmarkRunner
channels:
  - conda-forge
  - nodefaults
  - pytorch
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - cpuonly
  - onnx
  - tensorflow==2.15.*
  - keras==2.15.*
  - tf-keras==2.15.*
  # We don't like conda-forge's opencv packages, because they don't include
  # type stubs
  - pip:
    - opencv-python
    - ai-edge-model-explorer